### ISSUE TITLE
Nginx: domain aliases

### ISSUE THREAD

**Issue by vlunov-spryker** [spryker/devvm#15]
Please consider configuring default aliases for www subdomains for all applications. In the documentation we might have links with "www" and without "www". This can be achieved if 

https://github.com/spryker/saltstack/blob/a1c2c410cdbbee7ad660a857f1f8fad4afd32cc0/base/spryker/files/etc/nginx/sites-available/XX-yves.conf#L12

and

https://github.com/spryker/saltstack/blob/a1c2c410cdbbee7ad660a857f1f8fad4afd32cc0/base/spryker/files/etc/nginx/sites-available/XX-zed.conf#L12

are modified accordingly to the documentation http://nginx.org/en/docs/http/server_names.html. E.g.

`
server_name (www\.)?{{ settings.environments[environment].stores[store].zed.hostname }};
`

Please double-check, for Yves it will be a bit more complicated, the join filter has to be replaced with something else.

After adding these aliases, "www" can be removed from here https://github.com/spryker/pillar/blob/598f5ef0353105ed5b8fc8e9dda1702fa4371839/dev/app/init.sls#L139 and all the domains should be both accessible with and without "www".

Please do not forget to add these to host entires of the host machine. 
Thank you!

**Comment by marek-obuchowicz** [comment]
For Yves we can specify multiple vhost names directly in pillar, it's an array (https://github.com/spryker/pillar/blob/598f5ef0353105ed5b8fc8e9dda1702fa4371839/dev/app/init.sls#L139) - we can add there one (or more) additional lines.
For Zed i don't think it's a good change regarding hosting environments and SSL certificates. Typical wildcard certificate includes `domain.com` and `*.domain.com`, but it's only one-level - certificates like `*.*.domain.com` are not available.

In real life projects used to use following names:
Yves:
  - www.domain.com
  - domain.com
  - www.second-domain.com
  - second-domain.com

and just one for zed:
 - zed.domain.com
because www.zed.domain.com won't be allowed by certificate `*.domain.com`

That's also the reason why staging / qa envs very often have names like:
 - www-staging.domain.com
 - zed-staging.domain.com

**Comment by vlunov-spryker** [comment]
Certificates are not relevant for dev environments.

**Comment by marek-obuchowicz** [comment]
Yes, agreed. But please keep in mind that they are relevant for production environments and I'd rather prefer not introducing features on dev, which will be misleading for later qa/staging/production setups

**Comment by marek-obuchowicz** [comment]
Build #57 in progress...

**Comment by hhebbo** [comment]
done
