### ISSUE TITLE
RabbitMQ Repo URL Seems to not work

### ISSUE THREAD

**Issue by ashajjar** [spryker/devvm#89]
``` bash
apt-get update
```

throws an error

```
Reading package lists...
[ERROR   ] stderr: E: Failed to fetch https://dl.bintray.com/rabbitmq-erlang/debian/dists/buster/InRelease  403  Forbidden [IP: 3.127.93.119 443]
E: The repository 'https://dl.bintray.com/rabbitmq-erlang/debian buster InRelease' is not signed.
[ERROR   ] retcode: 100
[ERROR   ] {'pid': 15248, 'retcode': 100, 'stdout': 'Get:1 https://download.docker.com/linux/debian buster InRelease [54.0 kB]\nGet:3 https://deb.nodesource.com/
```

**Comment by stanislavrussu** [comment]
Hello,

RabbitMQ changed its repository URL. That's why you get this error. We're aware of this change and will include it in future releases. Please use `deb http://ppa.launchpad.net/rabbitmq/rabbitmq-erlang/ubuntu bionic main` instead of `deb https://dl.bintray.com/rabbitmq-erlang/debian buster erlang-22.x` for now. Moreover, instead of `key_url: https://github.com/rabbitmq/signing-keys/releases/download/2.0/rabbitmq-release-signing-key.asc` we'll use:
```
keyid: F77F1EDA57EBB1CC
keyserver: keyserver.ubuntu.com
```

Thank you!
